# Generated by Django 4.1.4 on 2022-12-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Republica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_republica', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero_da_republica', models.PositiveIntegerField()),
                ('valor', models.PositiveIntegerField()),
                ('quantidade_de_quartos', models.PositiveIntegerField()),
                ('quantidadedebanheiros', models.PositiveIntegerField()),
                ('quantidade_de_vagas_garagem', models.PositiveIntegerField()),
                ('regras_da_república', models.TextField(max_length=2000)),
                ('contato', models.CharField(max_length=20)),
                ('nome_anunciante', models.CharField(max_length=60)),
                ('descrição', models.TextField(max_length=2000)),
                ('fotos', models.ManyToManyField(to='plataforma.imagem')),
            ],
        ),
    ]
