# Generated by Django 4.1.4 on 2022-12-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='republica',
            old_name='quantidadedebanheiros',
            new_name='quantidade_de_banheiros',
        ),
    ]
