# Generated by Django 4.1.4 on 2022-12-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_contato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='republica',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
