# Generated by Django 4.1.5 on 2023-01-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_rename_nome_anunciante_republica_nome_do_anunciante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='republica',
            name='fotos',
        ),
        migrations.AddField(
            model_name='republica',
            name='foto1',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
