# Generated by Django 4.1.5 on 2023-01-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_remove_republica_fotos_republica_foto1_delete_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='republica',
            name='foto2',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='republica',
            name='foto3',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='republica',
            name='foto4',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='republica',
            name='foto5',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
